### ISSUE TITLE
npm install not working

### ISSUE THREAD

**Issue by pankaj-arunsingh** [DeborahK/Angular2-GettingStarted#1]
I downloaded the zip file and extracted it. I am trying to do npm install at the directory path where my APM folder is but I am getting the below error. Initially everything started to install properly but after this error I am not able to proceed.
![error](https://cloud.githubusercontent.com/assets/8179097/14447161/639d597c-00a0-11e6-8bfd-15ee2658be9c.JPG)
![error1](https://cloud.githubusercontent.com/assets/8179097/14447151/448a5a76-00a0-11e6-9525-32d913dbe9bb.JPG)

Kindly help. !!

**Comment by DeborahK** [comment]
Have you seen this: http://blogs.msmvps.com/deborahk/angular-2-getting-started-problem-solver/
Let me explain know whether this removes your issue.

**Comment by DeborahK** [comment]
Have not heard back, so assume the problem has been resolved. Please reopen if that is not the case.

**Comment by pankaj-arunsingh** [comment]
Apologies for late reply. I got it installed after having .typingsrc file. But now after typing npm start, I am facing another issue:-
![error-file](https://cloud.githubusercontent.com/assets/8179097/14625210/6c3f6bcc-0624-11e6-858b-3c3f2f9d6dbe.JPG)

Please help again.

**Comment by DeborahK** [comment]
Can you ensure that you have a recent version of npm installed?

**Comment by applicauy** [comment]
Hi, I am following the steps you mention in your video at pluralsight, so, when I run npm start I got this error:

Cannot read property 'config' of null
TypeError: Cannot read property 'config' of null
    at Class.run (C:\Users\Raul\Downloads\Angular-GettingStarted-master\APM-Start\node_modules
    \angular-cli\tasks\serve.js:22:61)
    at C:\Users\Raul\Downloads\Angular-GettingStarted-master\APM-Start\node_modules\angular-
    cli\commands\serve.run.js:22:22
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Can you help me with this please.

**Comment by DeborahK** [comment]
This is often caused by a missing `.angular-cli.json` file. On some systems, the "." in front of the file name either hides or does not copy the file.

Please ensure that you have the .angular-cli.json file in the root project folder,

![image](https://user-images.githubusercontent.com/7987365/33443079-87407eea-d5ab-11e7-9a62-90139954a0bf.png)
