### ISSUE TITLE
10. Retrieving Data Using Http -- Cannot retrieve data correctly

### ISSUE THREAD

**Issue by aleksmaksiuta** [DeborahK/Angular2-GettingStarted#10]
So, I walk along videos and trying to write all by myself. It appears that data via doesn't retrieve correctly. I have a long error stack trace, but in the end I get data in console, but it doesn't appear at screen. I've tryied to CTRL+C and CTRL+V final code in my files, but get same errors
![err](https://cloud.githubusercontent.com/assets/13423924/16443512/f48ef11a-3de1-11e6-8291-567931257e86.PNG)
![err2](https://cloud.githubusercontent.com/assets/13423924/16443511/f48ebfd8-3de1-11e6-8c5f-c21999d7a755.PNG)

**Comment by aleksmaksiuta** [comment]
All seems legit in Chapter 11 when we add routes to project. Data retrieves correctly and shows as it should be.

**Comment by DeborahK** [comment]
For your first issue, I would guess that you are missing the first part of the If condition in your HTML:
` <table class='table' *ngIf='products && products.length'>`

**Comment by aleksmaksiuta** [comment]
Oh, yep. Thanks, It was not so easy to notice that :)
