### ISSUE TITLE
ASP.Net Core version with Angular RC3?

### ISSUE THREAD

**Issue by kjartanvalur** [DeborahK/Angular2-GettingStarted#11]
Hi.
Thanks for a great Pluralsight course and excellent examples. Can you please do a ASP.Net Core version with Angular RC3? It would also be nice to have a angular-cli version with ASP.Net Core. I´m really having trouble getting things to work with Visual Studio 2015 and ASP.Net Core.

Thanks in advance.

**Comment by DeborahK** [comment]
Have you seen this: http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/
