### ISSUE TITLE
Error while installing libraries 

### ISSUE THREAD

**Issue by DevNamanGupta** [DeborahK/Angular2-GettingStarted#13]
I am attaching the screenshot of terminal and debug log file . Please have a look

![errornpm](https://cloud.githubusercontent.com/assets/13780776/16885907/9b99118e-4aee-11e6-9dad-2e055424ee18.png)

[npm-debug.log.tar.gz](https://github.com/DeborahK/Angular2-GettingStarted/files/366679/npm-debug.log.tar.gz)

**Comment by DeborahK** [comment]
Is this when trying to use npm install? I'd highly recommend updating your version of node.

**Comment by DevNamanGupta** [comment]
yes it was when i used npm install but now as you recommended , i updated my node version and its good now . I am able to run smoothly . Thank You !
