### ISSUE TITLE
Detail info on Nested routes, Authentication

### ISSUE THREAD

**Issue by dhiraj1mumbai** [DeborahK/Angular2-GettingStarted#15]
Hello Deborah,

Many thanks for your pluralsite course for Angular 2 and this GitHub Repo.

I would like to know more about, how to do nested routing, managing Authentication session of user.

I am also confused about '...' syntax in routing.

Please provide some insights.

**Comment by DeborahK** [comment]
Glad you have found it useful! Your best bet for questions such as this is the discussion tab for the course that you can find here: https://app.pluralsight.com/library/courses/angular-2-getting-started/discussion
The issue section here is for issues with the sample code provided here.
Thanks!
