### ISSUE TITLE
Cannot find module 'angular/core'.

### ISSUE THREAD

**Issue by amjad381** [DeborahK/Angular2-GettingStarted#16]
Folder: APM - Start
app.component.ts should be changed from
import { Component } from 'angular/core';
to
import { Component } from 'angular2/core';

**Comment by DeborahK** [comment]
App.component.ts is not provided in APM - Start. That is a file you build yourself as part of the associated hands on course.

**Comment by amjad381** [comment]
Wow, that was fast. Thanks for pointing out.
Btw, love the way you teach (Y)

**Comment by DeborahK** [comment]
Thank you!
