### ISSUE TITLE
Error when doing npm install

### ISSUE THREAD

**Issue by allenz0810** [DeborahK/Angular2-GettingStarted#25]
I have issue with proxy when it comes to typings install, can you walk me through?

I have solve npm and vs code proxy issue.

For npm proxy issue - 
npm config set proxy http://proxy.yourcompanyname.com:5050
npm config set https-proxy http://proxy.yourcompanyname.com:5050

for vs code proxy issue -
Go to File -> Preferences -> User Settings 
On the right side folder (setting.json) you add
// Place your settings in this file to overwrite the default settings

"http.proxy": "http://proxy.yourcompanyname.com:5050/",
"https.proxy": "http://proxy.yourcompanyname.com:5050/",
"http.proxyStrictSSL": false

**Comment by DeborahK** [comment]
So your issues are resolved at this point then? I'll add your fix to my blog post. I'd be happy to give you credit for the fix if you'd like to give me your name.
Thanks!

**Comment by DeborahK** [comment]
And can you tell me the error you saw before you made this fix so I can include it in the post? Thanks!

**Comment by allenz0810** [comment]
at this point my issue is not solve yet. the install stop at typings install.

![image](https://cloud.githubusercontent.com/assets/5561722/19574051/a2b9d294-96d6-11e6-9d14-73afb8013f55.png)

**Comment by allenz0810** [comment]
For VS Code if you not config the proxy, you will not able to see any extensions.

![image](https://cloud.githubusercontent.com/assets/5561722/19574171/1f489782-96d7-11e6-9970-776ea3871bba.png)

**Comment by allenz0810** [comment]
By the way what is credit  mean and you mention my name like github user name or real name?

**Comment by DeborahK** [comment]
I just added some detail to my blog here: http://blogs.msmvps.com/deborahk/angular-2-getting-started-problem-solver Let me know if anything there helps you out. (I don't have a corporate proxy so I can't try these out myself.)

**Comment by DeborahK** [comment]
I could use either name you'd like to provide ...

**Comment by allenz0810** [comment]
you can just use my github name allenz0810.
