### ISSUE TITLE
Not able to implement Guards

### ISSUE THREAD

**Issue by neerajkumarnj** [DeborahK/Angular2-GettingStarted#26]
Hi,
I tried to do exactly what you have done. After adding code for Guards, When I normally navigate in app, everything works fine (Navigating via link and no URL changing manually in browser).

But when i am on Product Details Page and i change the Product ID to some random text i.e. "localhost:3000/product/5" to "localhost:3000/product/werfsd"

From below screen:
![image](https://cloud.githubusercontent.com/assets/3349521/19688206/587333ce-9ae6-11e6-8b6e-1008188d29c5.png)

After changing, I get errors like:
![image](https://cloud.githubusercontent.com/assets/3349521/19688171/270f0240-9ae6-11e6-95d3-90c467093e08.png)

Also, If i am on "localhost:3000/welcome" and do a manual refresh from browser button. My Url gets changed to "localhost:3000/welcome/welcome" with some errors in Console.
![image](https://cloud.githubusercontent.com/assets/3349521/19688271/aaab4816-9ae6-11e6-9467-3061d99ce0ea.png)
![image](https://cloud.githubusercontent.com/assets/3349521/19688291/c17148e8-9ae6-11e6-84e1-07e765a5426d.png)

Why does this happens? What am i missing ?

**Comment by DeborahK** [comment]
Can you post the code for your routes?

**Comment by neerajkumarnj** [comment]
This is the code for my module file::

`import { NgModule } from '@angular/core';`
`import { BrowserModule } from '@angular/platform-browser';`
`import { FormsModule } from '@angular/forms';`
`import { HttpModule } from '@angular/http';`
`import { RouterModule } from '@angular/router';`

`import { AppComponent }  from './app.component';`
`import { ProductListComponent } from './products/product-list.component';`
`import { ProductFilterPipe } from './products/product-filter.pipe';`
`import { StarComponent } from './shared/star.component';`
`import { ProductDetailComponent } from './products/product-detail.component';`
`import { WelcomeComponent } from './home/welcome.component';`
`import { ProductDetailGuard } from './products/product-guard.service';`

`@NgModule({`
  `imports: [ BrowserModule,`
             `FormsModule,`
             `HttpModule,`
             `RouterModule.forRoot([`
                `{ path:'products', component: ProductListComponent },`
                `{ path: 'product/:id', canActivate: [ ProductDetailGuard ] , component: ProductDetailComponent },`
                `{ path: 'welcome', component: WelcomeComponent },`
                `{ path: '', redirectTo:'welcome', pathMatch: 'full' },`
                `{ path: '**', redirectTo: ' welcome', pathMatch: 'full' } `                     
            ` ])],`
  `providers:[ ProductDetailGuard],`
  `declarations: [ AppComponent, ProductListComponent, ProductFilterPipe, StarComponent, ProductDetailComponent, WelcomeComponent ],`
  `bootstrap: [ AppComponent ]`
`})`
`export class AppModule { }`

**Comment by neerajkumarnj** [comment]
Hi Deborah, did you get any ideas ?

**Comment by DeborahK** [comment]
Does this work for you if you use the Final version of the code provided here? Do you have access to a file compare utility that you could compare your code files to those Final versions?

**Comment by neerajkumarnj** [comment]
I do have access to the file compare utility. I will try the comparison and will update here.

**Comment by DeborahK** [comment]
Were you ever able to make this work? Can I close the issue?

**Comment by DeborahK** [comment]
I have not heard anything back so am closing this issue. Please let me know if you are still having problems and we can reopen it.
