### ISSUE TITLE
Error in refactoring to separate the routing responsibilities

### ISSUE THREAD

**Issue by jrmora** [DeborahK/Angular2-GettingStarted#27]
Hi Deborah, 
At the end of the "Angular Modules - Revisiting AppModule" clip, you suggest a refactoring to separate the routing responsibilities in two new Modules.... well, it doesn't work (and I haven't found the problem yet)

I follow the indications exactly as shown on slides, but the problem is that nothing happens when you click on the ProductList anchor.  (Yes, maybe is an import, but I have reviewed them all)

I attach images with the modifications:

1) app.module.ts
![app module ts](https://cloud.githubusercontent.com/assets/9900351/20034009/539409fc-a386-11e6-9ee1-050db919e4ab.png)
2) app-routing.module.ts
![app-routing module ts](https://cloud.githubusercontent.com/assets/9900351/20034029/b50e4512-a386-11e6-87c4-343f465b9e11.png)
3) product.module.ts
![product module ts](https://cloud.githubusercontent.com/assets/9900351/20034035/eecb1226-a386-11e6-9294-d302e0d8d30c.png)
4) product-routing.module.ts
![product-routing module ts](https://cloud.githubusercontent.com/assets/9900351/20034042/491ef148-a387-11e6-957f-0c6512247674.png)

Thanks,

**Comment by jrmora** [comment]
**Note**: 
If we remove 
`{ path: '**', redirectTo: 'welcome', pathMatch: 'full' }`
 it works... but then we lost that functionality

**Comment by DeborahK** [comment]
Do you see any messages in the F12 developer tools.

**Comment by jrmora** [comment]
No messages

**Comment by jrmora** [comment]
I work with your last Final version, and I put **only** the lines of your slides.  :)  (by the way)

**Comment by jrmora** [comment]
Well,  I've found a way to make it work:
transfer the responsability of  "**path: '**', redirectTo: 'welcome'**"  to the ProductRoutingModule:

`RouterModule.forChild([
      { path: 'products', component: ProductListComponent },
      { path: 'product/:id',
        canActivate: [ProductDetailGuard],
        component: ProductDetailComponent
      },
      { path: '**', redirectTo: 'welcome', pathMatch: 'full' }
    ])`

but I'm not sure if it's an ugly solution.   :)

**Comment by DeborahK** [comment]
It looks then like an ordering problem. Angular processes the routes in order. If it sees the wildcard route before the product routes it will never see the product routes.
My working code is at the office and I won't be back there until Friday. But you could try switching these two lines:
ProductModule
AppRoutingModule

**Comment by jrmora** [comment]
You're absolutely right.... that solves the problem.  

Thank you! (Nice weekend)

**Comment by DeborahK** [comment]
Great!
