### ISSUE TITLE
not generating .js file automatically

### ISSUE THREAD

**Issue by neoms21** [DeborahK/Angular2-GettingStarted#3]
Hi Deborah,

I followed the video and did the steps exactly same as yours but in my case adding the .ts doesn't generate the .js file automatically either in VS Code or webstorm. If I do npm start again, then js file is generated fine. I was just wondering have I missed something.

Thanks

**Comment by DeborahK** [comment]
You need to use 'npm start' every time you work on the project. That is what starts up the TypeScript compiler.

**Comment by neoms21** [comment]
Thanks for replying Deborah. My 'npm start' command is in running mode when I'm adding .ts file.
Do I have to restart 'npm start' after every addition of .ts file ?
