### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by swapnil-ranjan** [DeborahK/Angular2-GettingStarted#30]
Hi,

I am facing CORS error even after adding all the required headers.

 headers= new Headers();
         
    createAuthorizationHeader(headers: Headers) {
    headers.append('Access-Control-Allow-Origin', '*');
    headers.append('Access-Control-Allow-Headers', 'Content-Type');
    headers.append('Access-Control-Allow-Methods', 'GET');    
  }

    getProducts(): Observable<ISurgeon[]> {
        return this._http.get(this._productUrl,this.createAuthorizationHeader)
            .map((response: Response) => <ISurgeon[]> response.json())
            .do(data => console.log('All: ' +  JSON.stringify(data)))
            .catch(this.handleError);
    }

**Comment by DeborahK** [comment]
Check out this link for info on CORS: http://stackoverflow.com/questions/34790051/how-to-create-cross-domain-request-angular-2

**Comment by swapnil-ranjan** [comment]
Thanks for the help.
