### ISSUE TITLE
Unable to display full-list on native browser(mobile)

### ISSUE THREAD

**Issue by shah-smit** [DeborahK/Angular2-GettingStarted#36]
Its a great resource. Works perfectly fine on my chrome (mobile and web) but the native internet(android) it just display the first record the other doesnt. 

Thanks.

**Comment by DeborahK** [comment]
Have you seen the list of browser versions supported by Angular shown here: https://github.com/angular/angular

**Comment by shah-smit** [comment]
Thank you for reply. Looks like the device is supported. I guess it is do with routing. Rest all seem to work perfectly fine. 

Ref: https://angular.io/docs/ts/latest/guide/browser-support.html

**Comment by DeborahK** [comment]
Where you ever able to resolve this? Can we close this issue?

**Comment by shah-smit** [comment]
No. It is still on-hold.
