### ISSUE TITLE
I am not able to run the code using Visual studios 2015

### ISSUE THREAD

**Issue by venkataditya5** [DeborahK/Angular2-GettingStarted#37]
Hi Every one,
I have downloaded the files. But When I open the folder from Visual studios . I don't see any files.
I have downloaded the node.js also.

I did not execute the npm command .Is that the Issue.

Thank you 
Venkat

**Comment by DeborahK** [comment]
The files are not set up to be automatically handled by Visual Studio. Please follow the instructions here: https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html
