### ISSUE TITLE
No products being returned after implementing http request

### ISSUE THREAD

**Issue by wcski** [DeborahK/Angular2-GettingStarted#38]
Just completed the Retrieving Data using HTTP module and no products are being returned in the product list. Getting a 404 "Cannot get /null" error in the browser console. No errors being indicated in VS code.

**Comment by wcski** [comment]
Silly error on my part. fixed.

**Comment by DeborahK** [comment]
Glad you resolved it!

**Comment by wcski** [comment]
Me too! 

The error was in this line of my service class:

private _productUrl: 'api/products/products.json';

since the above is valid TS, it wasn't cluing me in to the fact that i need an = operator to properly assign the path to the variable. 

Thanks again for your responsiveness and your work on the course.
