### ISSUE TITLE
website refreshing twice.

### ISSUE THREAD

**Issue by shah-smit** [DeborahK/Angular2-GettingStarted#39]
When tried doing `npm start` I am seeing the website loading twice. May I know why?

**Comment by harshp2035** [comment]
Webpage are refreshing by script injected in the page or by a browser plugin. so every time website are refreshing twice.

**Comment by shah-smit** [comment]
Thanks for the revert @harshp2035

 And how can I avoid it?

**Comment by harshp2035** [comment]
You Can't avoid it as per my knowledge cause for security purpose each and every time data got ping so... but you can check it your browser setting and try to block that. @shah-smit

**Comment by DeborahK** [comment]
Which files are you using? APM - Start? APM - Final? I just tried the files from APM - Final and I am not seeing this behavior.

**Comment by shah-smit** [comment]
Thanks for follow-up. What browser are you using? - because I am seeing the behaviour for Google-Chrome and Safari.

**Comment by DeborahK** [comment]
I am using Google-Chrome on Windows. I am using the APM - Final files with the packages for Angular 2. My lite-server version is 2.2.2.
