### ISSUE TITLE
Acme Favicon displaying for all my other apps

### ISSUE THREAD

**Issue by ssuhas76** [DeborahK/Angular2-GettingStarted#40]
Hi Deborah,

I completed your Angular getting started and am building my own app using quick start guide. As you already the default URL in the browser will be localhost:3000. The app runs fine but I am getting the ACME favicon on my app as well. I am not sure why this happening. Please help.

Regards,
Suhas

**Comment by DeborahK** [comment]
The favicon.ico file is in the root folder of the application. Just replace it with whatever icon you want for your application.

**Comment by ssuhas76** [comment]
I replaced the favicon and it is working now. But I am still not sure how Acme favicon shows up for my app. Both are in different folder but the URL is the same. I run apps at different times of course. Is it a caching issue?

**Comment by DeborahK** [comment]
Maybe a caching issue? When you run the application, open the developer tools, click the Network tab, and check the "Disable cache" button. Then see if that changes what you are seeing.

**Comment by DeborahK** [comment]
Can I close this issue then at this point?

**Comment by ssuhas76** [comment]
Yup...It is working now!! Thanks a lot

**Comment by ssuhas76** [comment]
Hi Deborah,

Is it possible to have more than on pipes. In the ACM project we created a custom pipe to filter with a string. Can we write another custom pipe to sort by value of amount?

**Comment by DeborahK** [comment]
Yes, you can write multiple pipes. Or you can write one pipe that takes in multiple criteria.

`      return value.filter((acct: IAcct) => (field1Filter ? acct.field1.toLocaleLowerCase().indexOf(field1Filter) !== -1 : true)
            && (field2Filter ? acct.field2.toLocaleLowerCase().indexOf(field2Filter) !== -1 : true)
            && (field3Filter ? acct.field3.toLocaleLowerCase().indexOf(field3Filter) !== -1 : true)
            && (field4Filter ? acct.field4.toLocaleLowerCase().indexOf(field4Filter) !== -1 : true))`

**Comment by ssuhas76** [comment]
OK....I also meant multiple pipes in a signle file? Like one for filtering text and one for sorting based on amount.

Will the below code work?

@Pipe({
-----------
)}
export class KickStarterFilterPipe implements PipeTransform{

//code for filtering text
}

@Pipe({
-----------
)}
export class KickStarterSortPipe implements PipeTransform{
//code for sorting product based on amount
}


P.S. Is it OK if I ask questions here because this is not an issue. I am just asking for extra information since the discussion page has been disabled o Pluralsight
