### ISSUE TITLE
http Js FIles

### ISSUE THREAD

**Issue by srisrim** [DeborahK/Angular2-GettingStarted#41]
Where can i find http.dev.js,angular.dev.js and rx.js

**Comment by DeborahK** [comment]
May I ask what you are trying to do that you need the location of these files? Have you run 'npm install'?

**Comment by srisrim** [comment]
npm installed already while i try to include these files from node_modules I didnt find these files in that. Somehow i got these files and i tried to import in app.component.ts file. But then It Throws error as below:
" app/app.component.ts(3,10): error TS2305: Module '"D:/R&D/My-App/node_modules/@angular/http/index"' has no exported member 'HTTP_PROVIDERS'."

**Comment by DeborahK** [comment]
Ensure you are in the directory containing the package.json file and run 'npm install'

**Comment by srisrim** [comment]
I have ensured that the package.json file is included in this project. Still the issue exists

**Comment by srisrim** [comment]
Now Another Issue FInd the attachment below.
![ts1005](https://cloud.githubusercontent.com/assets/9192395/24793137/8458dd20-1b9e-11e7-94aa-1701538de04a.png)

I have Upgraded Typescript but the issue exists.

**Comment by DeborahK** [comment]
This does not look like the code from this repository?

**Comment by srisrim** [comment]
This is from From the same Repo and with some custom Html Functionalities.

**Comment by DeborahK** [comment]
This repo looks like this ...
![image](https://cloud.githubusercontent.com/assets/7987365/24870009/d33fa676-1dc9-11e7-9405-e0ba94f5f259.png)

**Comment by srisrim** [comment]
Issue is due to Jasmine I agree but that comes when I install npm. Jasmine folder is inside node_modules.

**Comment by DeborahK** [comment]
Since this is definitely not the code from my repo, consider instead posting any questions/issues to stackoverflow. The experts there are often quick to help. Best wishes!
