### ISSUE TITLE
any example/seed for supporting asp.net core production ready?

### ISSUE THREAD

**Issue by sivamamidi-REISys** [DeborahK/Angular2-GettingStarted#42]
any example/seed for supporting asp.net core production ready?

**Comment by DeborahK** [comment]
Have you seen this: https://www.hanselman.com/blog/dotnetNewAngularAndDotnetNewReact.aspx

**Comment by sivamamidi-REISys** [comment]
it's definitely offline topic from this thread, Yes, i have seen it, above seed project using webpack/npm, actually some of the modules are developed using systemjs, how to include them as external?

**Comment by DeborahK** [comment]
Have you see this: https://angular.io/docs/ts/latest/guide/webpack.html

**Comment by sivamamidi-REISys** [comment]
Thank you. i really like your pluralsight tutorials(getting started, reactive forms and routing).

**Comment by DeborahK** [comment]
Thanks! Can we close this issue at this point?
