### ISSUE TITLE
Not importing Angular Router

### ISSUE THREAD

**Issue by wcski** [DeborahK/Angular2-GettingStarted#45]
In the "Navigation and Routing Basics: Placing the Views" section of the course we implement `routerLink` and `router-outlet` in our app.component.ts, but we aren't importing any routing services from Angular, so the page throws errors and doesn't display.

**Comment by wcski** [comment]
Non-issue. I must have been asleep during the Routing Configuration video. Those services, as well as the routing path definitions, are contained in that video.

**Comment by DeborahK** [comment]
Glad you resolved it!
