### ISSUE TITLE
I suddenly get an error message when doing npm start

### ISSUE THREAD

**Issue by elfworld** [DeborahK/Angular2-GettingStarted#46]
Hi. After a week's break from the Pluralsight course, I was going to start again today. But when I do the command "npm start," I get the following message:
17 error Windows_NT 6.1.7601
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.10.2
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error product-management@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
22 error Exit status 2
23 error Failed at the product-management@1.0.0 start script 'tsc && concurrently "tsc -w" "lite-server" '.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the product-management package,
23 error not with npm itself.

I haven't done any changes to any of the course catalogues since the last chapter. What am I missing here?

**Comment by DeborahK** [comment]
Is it possible you are not in the appropriate directory when you execute the command? You need to be in the folder containing the package.json file.

**Comment by elfworld** [comment]
I'm starting it from the same folder that I've always started it from. And package.json is in that folder.

I downloaded all the files from your github again, and installed it on another directory on my computer. I did npm install and the npm start. Everything worked just fine. So something must have happened to my old installation. 

I did a test:

I slowly copied files from the old installation where I've added and changed files while following the course module (the installation that doesn't work anymore) over to the new one. After copying each file I did npm start again. When I had copied over the file called product.service.js, the error also started to appear in the new installation. I've no idea why. It could be a coincidence of course.  

Seems like I just have to start all over again. Or use the FINAL-folder for the rest of the course. If you don't have any other suggestions

**Comment by DeborahK** [comment]
When you ran npm start ... if you look after the command in the console, are there any errors listed before the info you posted above? Some syntax errors will prevent it from starting.

Also, the service should be `product.service.ts`, not `.js`

**Comment by elfworld** [comment]
There's both a .ts and a .js file called product.service.

Here's the complete output when writing npm start:
![image](https://cloud.githubusercontent.com/assets/28048032/25460288/eb62956c-2ae2-11e7-978d-25b8298b3956.png)

**Comment by DeborahK** [comment]
Ah! You have 3 syntax errors. They are shown immediately above the first npm error line.

**Comment by DeborahK** [comment]
Were you able to resolve your syntax errors? Can we close this?

**Comment by elfworld** [comment]
Sorry for note getting back to you before now, but I didn't have the chance to check it before now.

I can't believe that I hadn't seen tat error on top of all the red ERR's.

Everything works just fine now. Thank you very much!

**Comment by sguindi** [comment]
Hi im having the same issues:
npm start

> product-management@1.0.0 start /home/sharonco/projects/angular/apmFinal
> tsc && concurrently "tsc -w" "lite-server" 

node_modules/rxjs/Subject.d.ts:24:5 - error TS2416: Property 'lift' in type 'Subject<T>' is not assignable to the same property in base type 'Observable<T>'.
  Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
    Type 'Observable<T>' is not assignable to type 'Observable<R>'.
      Type 'T' is not assignable to type 'R'.

24     lift<T, R>(operator: Operator<T, R>): Observable<T>;
       ~~~~


node_modules/typescript/lib/lib.d.ts:105:14 - error TS2300: Duplicate identifier 'PropertyKey'.

105 declare type PropertyKey = string | number | symbol;
                 ~~~~~~~~~~~


typings/globals/core-js/index.d.ts:3:14 - error TS2300: Duplicate identifier 'PropertyKey'.

3 declare type PropertyKey = string | number | symbol;
               ~~~~~~~~~~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! product-management@1.0.0 start: `tsc && concurrently "tsc -w" "lite-server" `
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the product-management@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sharonco/.npm/_logs/2019-07-24T12_53_45_029Z-debug.log


I have no idea how to continue

**Comment by DeborahK** [comment]
Please ensure you have downloaded the current code from *this* github folder. The error message you are seeing above is from a very old version of the code.

if you look in the package.json file, you should see this:

```
  "scripts": {
    "ng": "ng",
    "start": "ng serve -o",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
```

And *not* this:
tsc && concurrently "tsc -w" "lite-server" 

That has not been in the code for almost 2 years.

There are numerous copies of my code in other repositories on github that other developers have copied and not kept up to date.

Let me know if that resolves your issue.
