### ISSUE TITLE
APM_Final does not start

### ISSUE THREAD

**Issue by yogiahuja** [DeborahK/Angular2-GettingStarted#47]
APM_Final does not start. give below error

src/app/app.component.ts(1,27): error TS2307: Cannot find module '@angular/core'.
src/app/app.module.ts(1,26): error TS2307: Cannot find module '@angular/core'.
src/app/app.module.ts(2,31): error TS2307: Cannot find module '@angular/platform-browser'.
src/app/app.module.ts(3,28): error TS2307: Cannot find module '@angular/http'.
src/app/app.module.ts(4,30): error TS2307: Cannot find module '@angular/router'.
src/app/home/welcome.component.ts(1,27): error TS2307: Cannot find module '@angular/core'.
src/app/products/product-detail.component.ts(1,46): error TS2307: Cannot find module '@angular/core'.
src/app/products/product-detail.component.ts(2,40): error TS2307: Cannot find module '@angular/router'.
src/app/products/product-detail.component.ts(4,36): error TS2307: Cannot find module 'rxjs/Subscription'.
src/app/products/product-detail.component.ts(25,13): error TS7006: Parameter 'params' implicitly has an 'any' type.
src/app/products/product-detail.component.ts(37,13): error TS7006: Parameter 'product' implicitly has an 'any' type.
src/app/products/product-detail.component.ts(38,13): error TS7006: Parameter 'error' implicitly has an 'any' type.
src/app/products/product-filter.pipe.ts(1,38): error TS2307: Cannot find module '@angular/core'.
src/app/products/product-guard.service.ts(1,28): error TS2307: Cannot find module '@angular/core'.
src/app/products/product-guard.service.ts(2,61): error TS2307: Cannot find module '@angular/router'.
src/app/products/product-list.component.ts(1,36): error TS2307: Cannot find module '@angular/core'.
src/app/products/product-list.component.ts(30,28): error TS7006: Parameter 'products' implicitly has an 'any' type.
src/app/products/product-list.component.ts(31,28): error TS7006: Parameter 'error' implicitly has an 'any' type.
src/app/products/product.module.ts(1,26): error TS2307: Cannot find module '@angular/core'.
src/app/products/product.module.ts(2,29): error TS2307: Cannot find module '@angular/router'.
src/app/products/product.service.ts(1,28): error TS2307: Cannot find module '@angular/core'.
src/app/products/product.service.ts(2,32): error TS2307: Cannot find module '@angular/http'.
src/app/products/product.service.ts(4,28): error TS2307: Cannot find module 'rxjs/Observable'.
src/app/products/product.service.ts(21,17): error TS7006: Parameter 'data' implicitly has an 'any' type.
src/app/shared/shared.module.ts(1,27): error TS2307: Cannot find module '@angular/core'.
src/app/shared/shared.module.ts(2,30): error TS2307: Cannot find module '@angular/common'.
src/app/shared/shared.module.ts(3,29): error TS2307: Cannot find module '@angular/forms'.
src/app/shared/star.component.ts(2,38): error TS2307: Cannot find module '@angular/core'.
src/main.ts(2,40): error TS2307: Cannot find module '@angular/platform-browser-dynamic'.

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! product-management@1.1.0 build: `tsc -p src/`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the product-management@1.1.0 build script 'tsc -p src/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the product-management package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc -p src/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs product-management
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls product-management
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Neelofar\AppData\Roaming\npm-cache\_logs\2017-05-08T18_46_52_035Z-debug.log

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! product-management@1.1.0 prestart: `npm run build`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the product-management@1.1.0 prestart script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the product-management package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs product-management
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls product-management
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Neelofar\AppData\Roaming\npm-cache\_logs\2017-05-08T18_46_52_105Z-debug.log

**Comment by DeborahK** [comment]
Did you run `npm install` before `npm start`? If not, none of the libraries required for the application are yet installed.

**Comment by yogiahuja** [comment]
Yes I forgot to do install. Now it works fine. Thanks Deborah for getting back

Thanks
Yogi Ahuja


On May 8, 2017, at 5:33 PM, Deborah Kurata <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you run npm install before npm start? If not, none of the libraries required for the application are yet installed.

**Comment by DeborahK** [comment]
OK. Glad you resolve it. I'm closing the issue.

**Comment by yogiahuja** [comment]
Hi Deborah

I have downloaded your APM final and made some changes like change title. But the changes are not getting reflected. Please advice what could we doing wrong

Thanks
Yogi Ahuja


On May 8, 2017, at 5:36 PM, Deborah Kurata <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #47<https://github.com/DeborahK/Angular2-GettingStarted/issues/47>.

**Comment by DeborahK** [comment]
Did you run `npm start` again? Do you have browser caching turned off?

**Comment by yogiahuja** [comment]
APM start works fine if we change it is reflecting but APM final when we make changes it does not reflects. Yes I tried doing APM start

Thanks
Yogi Ahuja


On May 15, 2017, at 10:25 AM, Deborah Kurata <notifications@github.com<mailto:notifications@github.com>> wrote:


Did you run npm start again? Do you have browser caching turned off?

**Comment by DeborahK** [comment]
When you downloaded APM - final, did you run `npm install` to install all of the packages?

When you run `npm start`, do you see any syntax errors appear in the console?

**Comment by yogiahuja** [comment]
Yes I did APM install and then APM start. In APM final folder I am noticing that even I did APM install .js files did not appeared however in APM start I see those js files appear after APM install.

Thanks
Yogi Ahuja


On May 15, 2017, at 10:38 AM, Deborah Kurata <notifications@github.com<mailto:notifications@github.com>> wrote:


When you downloaded APM - final, did you run npm install to install all of the packages?

When you run npm start, do you see any syntax errors appear in the console?

**Comment by DeborahK** [comment]
Do you mean in VS Code? That's because as part of the course we learn how to use VS Code to "hide" the .js files. So in the final folder, the .js files are hidden. 

Or do you mean in the folders? They won't appear in the folders until the code is compiled with `npm start`. If `npm start` is not running, it won't generate the .js files.

**Comment by yogiahuja** [comment]
I got it working . Somehow I end up clearing cache second time again to make it work. Thanks a lot for quick response

Thanks
Yogi Ahuja


On May 15, 2017, at 10:44 AM, Deborah Kurata <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you mean in VS Code? That's because as part of the course we learn how to use VS Code to "hide" the .js files. So in the final folder, the .js files are hidden.

Or do you mean in the folders? They won't appear in the folders until the code is compiled with npm start. If npm start is not running, it won't generate the .js files.

**Comment by DeborahK** [comment]
Glad to hear!

**Comment by harshilravi** [comment]
Hi DeborahK,

I have start learning Angular 4 with your Tutorial and also I am making same Application as you are used in Tutorial.
but right now I am stuck with little bit. Problem is that I am using "http" services in product.services.ts.
And I facing error regrading "get method".
Error message:-
"**ERROR in C:/Users/Jatin/Desktop/angular 4/Angular-GettingStarted-master/APM-Start/src/app/products/product.service.ts (18,26): Property 'get' does not exist on type
'typeof HttpClient**'." 

It would be great you can help me ASAP.

Thanks
Harshil Thakkar
