### ISSUE TITLE
Unit testing for the project

### ISSUE THREAD

**Issue by r0lan2** [DeborahK/Angular2-GettingStarted#48]
Hi @DeborahK ,
How hard is to include unit testing for this project? as far I see this project was created without these. Just for curiosity  I am trying find some useful blog post related with:" how to add tests to an angular 2 application".. some page talking about webpack.... but for this project doesn't apply.  Any advice :) ?

**Comment by DeborahK** [comment]
The best place to start is here: https://angular.io/docs/ts/latest/testing/

Let me know if that helps.

**Comment by r0lan2** [comment]
https://angular.io/docs/ts/latest/testing/setup.html is broken but I think this link should be good enough.
http://ericnish.io/blog/set-up-jasmine-and-karma-for-angularjs/

(My question was pointing out: what was the bes way to setup karma + jasmin framework for project like this .. where testing framework dependencies weren't installed at the begining)
Note: I love your pluralsight courses 👍

**Comment by DeborahK** [comment]
For a "real" application, I'd start with the Angular CLI. It automatically sets up the test files. If you want to incorporate this into my sample code ... you can run the CLI *first*, then copy the majority of the app folder contents to the Angular CLI-generated app. 

Make sense?

Also, I just reported the broken link. Hopefully someone will be able to fix it soon.
