### ISSUE TITLE
error occurs while routing

### ISSUE THREAD

**Issue by saisaraswathi** [DeborahK/Angular2-GettingStarted#49]
Uncaught TypeError: Cannot read property 'OpaqueToken' of undefined
    at router.umd.js:145
    at router.umd.js:9
    at router.umd.js:10
(anonymous) @ router.umd.js:145
(anonymous) @ router.umd.js:9
(anonymous) @ router.umd.js:10
(index):59 Live reload enabled.
(index):27 Error: ReferenceError: WelcomeComponent is not defined
	    at Object.eval (http://127.0.0.1:3000/app/app.component.js:29:61)
	    at eval (http://127.0.0.1:3000/app/app.component.js:35:4)
	    at eval (http://127.0.0.1:3000/app/app.component.js:36:3)
	    at eval (<anonymous>)
	Evaluating http://127.0.0.1:3000/app/app.component.js
	Evaluating http://127.0.0.1:3000/app/app.module.js
	Evaluating http://127.0.0.1:3000/app/main.js
	Error loading http://127.0.0.1:3000/app/main.js

**Comment by saisaraswathi** [comment]
I imported WelcomeComponent and included the scripts told in the course but unable to route..I didn't understand about opaque tokens?

**Comment by DeborahK** [comment]
You can get the code as of the end of each module using the Exercise files tab for the course. Then you can compare your files to mine to see if you have a typo or syntax error somewhere.

Note that Angular is case sensitive, so ensure your casing is correct.

**Comment by DeborahK** [comment]
Where you able to resolve this? Can we close this issue?

**Comment by saisaraswathi** [comment]
yeah ,i resolved. can close
