### ISSUE TITLE
"typings install" command fails in the starter kit

### ISSUE THREAD

**Issue by bhavya11** [DeborahK/Angular2-GettingStarted#50]
Hello,
On doing npm install to setup the project dependencies in the starter project, it fails while executing "typings install" command.

Configuration Details:
Code in the folder APM-Start

Node Version: 6.9.1, NPM version: 3.10.8

Attached the npm-debug-log that has the detailed error.
[npm-debug-log.txt](https://github.com/DeborahK/Angular2-GettingStarted/files/1074206/npm-debug-log.txt)

**Comment by narasimhasatti** [comment]
Hi ,

Even i am facing the same issue with "APM Start".Please help on this.
node@v6.9.5
npm@3.10.10

Regards,
Narasimha Satti

**Comment by DeborahK** [comment]
Yes, the typings installing continues to be an issue for some devs. There are some suggestions here: https://blogs.msmvps.com/deborahk/category/angular-course-problem-solver/

There are also some suggestions here: https://stackoverflow.com/questions/35662790/npm-post-install-typings-not-working-correctly/36887161#comment59504242_35904914

Another option is to use the APM-Start-Updates. It uses a different setup for installing the typings.

Let me know if something there was helpful for you.

**Comment by DeborahK** [comment]
Any luck resolving this issue?

**Comment by bhavya11** [comment]
Moved to NG4.

**Comment by DeborahK** [comment]
Thanks for the update. Hopefully you are able to move forward with working through the course!

**Comment by narasimhasatti** [comment]
![error](https://user-images.githubusercontent.com/8241443/27451247-0a72f6b8-57ac-11e7-97d2-c3818aa2321f.jpg)
Hi Deborahk,
Iam getting above mentioned typing install error on npm istall.
Please help me in resolving the issue.

Regards,
Narasimha satti

**Comment by narasimhasatti** [comment]
Hi Deborahk,

I have updated the Typing Node version and commited the package.json , issue was resolved for me.

Regards,
Narasimha Satti
