### ISSUE TITLE
top level folder spaces in names

### ISSUE THREAD

**Issue by samiujan** [DeborahK/Angular2-GettingStarted#8]
Top level folders have names in spaces etc "APM - Final Updated" etc. - it's a pain to have to write them from the cmdline - please use underscores/dashes instead of spaces

**Comment by DeborahK** [comment]
Great suggestion. I'll plan to do that when I update the course for the final Angular 2 release.

**Comment by sdruipeng** [comment]
>cd TAB 
then choose what you want.

**Comment by ankitavyas** [comment]
I have start using APM - Start.
I am still getting "Loading the app" and not getting anything else. I looked at following link, but no luck. Any other idea ?

 http://blogs.msmvps.com/deborahk/angular-2-getting-started-problem-solver/

**Comment by hesparza** [comment]
It would be great to have instructions on how to go further and prepare an actual deployment bundle out from an Angular 2 project like this one.

Awesome course in Pluralsight, thanks!

**Comment by DeborahK** [comment]
ankitavyas - Your comment does not belong here on the github issue request for renaming the folders. Please post your comment either as a separate issue here, or better as a comment here: 
https://app.pluralsight.com/library/courses/angular-2-getting-started/discussion
Thanks!

**Comment by DeborahK** [comment]
hesparza - Thank you so much for the kind words about the course!

**Comment by DeborahK** [comment]
I left the original files with the spaces because that is what is shown in the recording for the course. I did remove the spaces in the "updated" versions. Hope this helps.
