### ISSUE TITLE
Course disappeared from youtube

### ISSUE THREAD

**Issue by lukaVarga** [DeborahK/Angular2-GettingStarted#9]
Hi Deborah,

I was watching this course on Youtube a week ago and it was really an awesome one, the best I've found by far. Now, when I had the time to finish the rest of the tutorial (routes), I found it was removed.. Are you updating it to correspond with the Angular updates?

Best wishes,
Luka

**Comment by DeborahK** [comment]
Thank you so much for the kind words about the course. The person that posted it to youtube *stole* it from me, so it was taken down. You can find the actual course here: https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents

I am still waiting for some additional changes to Angular 2 that are coming so I will be updating the course later this summer.

**Comment by lukaVarga** [comment]
Hi Deborah,

I am sorry to hear it was stolen from you :( Thank you for the link. 

Best wishes,
Luka

**Comment by Fshamri** [comment]
Hello Deborah,
https://app.pluralsight.com/library/courses/angular-2-getting-started/table-of-contents is  giving  403 Forbidden

**Comment by DeborahK** [comment]
Try just this: https://www.pluralsight.com/courses/angular-2-getting-started
But you have to have a Pluralsight membership to watch more than the intro. If you don't have a membership I can email you a free month membership number. I'd just need an email address.

**Comment by Fshamri** [comment]
Thank you DeborahK, my email address is: faizalshamri@gmail.com

**Comment by pketan40** [comment]
Hi Deborahk,

My Email  ID is *pketan40@gmail.com <pketan40@gmail.com>*

Regards,

Ketan Patel

**Comment by oyaglidere** [comment]
my email is oyaglidere@gmail.com

Ozgur YAGLIDERE
Kind regards / Saludos cordiales / Mit freundlichen Grüßen / Bien à vous /
Vriendelijke groeten / En iyi dileklerimle / наилучшими пожеланиями / Με
φιλικούς χαιρετισμούς / 親切的問候 /  مع أطيب التحيات / तरह का संबंध है / דש"ים
Its very simple to be happy! But.. its difficult to stay simple...
